# Can be used instead of the paths below
options:
  dcf_path: "@BUS_CONFIG_PATH@"
master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baudrate: 250
  reset_communication: false
  # sync_period: 10000

  # Custom added from debugging
  # product_code: 0x01C9C44A

defaults:
  dcf: "EDS_20014_Standard_CANopen_V212_01.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  polling: true
  period: 10
  diagnostics:
    enable: true
    period: 1000 # in milliseconds

  reset_communication: false


nodes:
  left_wheel:
    node_id: 0x1E
  right_wheel:
    node_id: 0x1F
