
controller_manager:
  ros__parameters:
      update_rate: 20  # Hz

      battery_state_sensor_mock_right_wheel:
        type: forward_command_controller/MultiInterfaceForwardCommandController
      battery_state_sensor_mock_left_wheel:
        type: forward_command_controller/MultiInterfaceForwardCommandController
      battery_state_broadcaster:
        type: battery_state_broadcaster/BatteryStateBroadcaster

      node_error_broadcaster:
        type: node_error_broadcaster/NodeErrorBroadcaster
      node_error_broadcaster_mock:
        type: forward_command_controller/MultiInterfaceForwardCommandController

      vda5050_safety_state_broadcaster_mock:
        type: forward_command_controller/MultiInterfaceForwardCommandController
      vda5050_safety_state_broadcaster:
        type: vda5050_safety_state_broadcaster/Vda5050SafetyStateBadcaster

battery_state_broadcaster:
  ros__parameters:
    state_joints: ["left_wheel", "right_wheel"]
    interfaces:
      left_wheel:
        battery_voltage: true
        battery_current: true
        battery_charge: false
        battery_percentage: false
        battery_power_supply_status: false
        battery_power_supply_health: false
        battery_present: false
      right_wheel:
        battery_voltage: true
        battery_current: true
        battery_charge: false
        battery_percentage: false
        battery_power_supply_status: false
        battery_power_supply_health: false
        battery_present: false

battery_state_sensor_mock_right_wheel:
  ros__parameters:
    joint: left_wheel
    interface_names:
      - battery_voltage
      - battery_current
battery_state_sensor_mock_left_wheel:
  ros__parameters:
    joint: right_wheel
    interface_names:
      - battery_voltage
      - battery_current

vda5050_safety_state_broadcaster:
  ros__parameters:
    fieldViolation_interfaces:
      - PLC_sensor1/fieldViolation
    eStop_manual_interfaces:
      - PLC_sensor1/eStopManual
    eStop_remote_interfaces:
      - PLC_sensor1/eStopRemote
    eStop_autoack_interfaces:
      - PLC_sensor1/eStopAutoack
vda5050_safety_state_broadcaster_mock:
  ros__parameters:
    joint: PLC_sensor1
    interface_names:
      - fieldViolation
      - eStopManual
      - eStopRemote
      - eStopAutoack

node_error_broadcaster:
  ros__parameters:
    interfaces:
      - right_wheel/emcy/error_code
      - right_wheel/emcy/error_register
      - right_wheel/emcy/manufacturer_error_code1
      - right_wheel/emcy/manufacturer_error_code2
      - right_wheel/emcy/manufacturer_error_code3
      - right_wheel/emcy/manufacturer_error_code4
      - right_wheel/emcy/manufacturer_error_code5
    severity: LEVEL_WARNING
    id: 1
    source: right_wheel_emcy
    type: default_type # what is this?

node_error_broadcaster_mock:
  ros__parameters:
    joint: right_wheel
    interface_names: 
      - emcy/error_code
      - emcy/error_register
      - emcy/manufacturer_error_code1
      - emcy/manufacturer_error_code2
      - emcy/manufacturer_error_code3
      - emcy/manufacturer_error_code4
      - emcy/manufacturer_error_code5