controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_caterpillar_controller:
      type: canopen_ros2_controllers/CanopenProxyController

    right_caterpillar_controller:
      type: canopen_ros2_controllers/CanopenProxyController


left_caterpillar_controller:
  ros__parameters:
    joint: left_caterpillar


right_caterpillar_controller:
  ros__parameters:
    joint: right_caterpillar
